
```{r}
library(here)
library(tidyverse)
library(sf)
library(stars)
library(tmap)
library(leaflet)
library(mapview)
library(rnaturalearth)
library(ggspatial)
```

```{r}
ei_points <- st_read(here("discussion", "data", "easter_island", "ei_points.gpkg")) |> 
  filter(type == "volcano")
ei_elev <- read_stars(here("discussion", "data", "easter_island", "ei_elev.tif"))
ei_borders <- st_read(here("discussion","data", "easter_island", "ei_border.gpkg"))
ei_roads <- st_read(here("discussion", "data", "easter_island", "ei_roads.gpkg"))
```



# Create a single-object map with tmap

```{r}
tm_shape(ei_borders) +
    tm_borders() +
    tm_title("Easter Island")
```



# Create a multiple-object map with tmap

```{r}
tm_shape(ei_elev) +
    tm_graticules(lwd = 0.5, col = "lightgray") +
    tm_raster(col.scale = tm_scale_continuous(values = "-rd_yl_gn"),
    col.legend = tm_legend("Elevation (m asl)")) +
tm_shape(ei_borders) +
    tm_borders() +
tm_shape(ei_roads) +
    tm_lines() +
tm_shape(ei_points) +
    tm_symbols(shape = 24, 
                size = "elevation", 
                size.legend = tm_legend("Volcanos (m asl)")) +
tm_compass(position = c("right", "top")) +
tm_scalebar() +
tm_title("Easter Island") 

```


# Create an interactive map with tmap


```{r}
#tmap_mode("view")

tm_shape(ei_elev) +
    tm_graticules(lwd = 0.5, col = "lightgray") +
    tm_raster(col.scale = tm_scale_continuous(values = "-rd_yl_gn"),
    col.legend = tm_legend("Elevation (m asl)")) +
tm_shape(ei_borders) +
    tm_borders() +
tm_shape(ei_roads) +
    tm_lines() +
tm_shape(ei_points) +
    tm_symbols(shape = 24, 
                size = "elevation", 
                size.legend = tm_legend("Volcanos (m asl)")) +
tm_compass(position = c("right", "top")) +
tm_scalebar() +
tm_title("Easter Island") 

tmap_mode("plot")
```


# Create a multiple-object map with `ggplot`

Given solution from [website](https://eds-223-geospatial.github.io/course-materials/discussions/week1-discussion.html)
```{r}

# extract lat & long from geom column 
volcanoes_point <- ei_points %>%
  mutate(lon = unlist(map(ei_points$geom,1)), # longitude = first component (x)
         lat = unlist(map(ei_points$geom,2))) # latitude = second component (y)


ggplot() +
  # first add Easter Isand borders
  geom_sf(data = ei_borders, color = "#212529") +
  # add elevation raster
  geom_stars(data = ei_elev) +
  scale_fill_distiller(name = "Elevation (m asl)", # legend title with units
                       palette = "RdYlGn",         # red-yellow-green palette (no need to reverse)
                       na.value = "lightblue") +  # set NA color (background ocean)
  # add road vector
  geom_sf(data = ei_roads, color = "black") +
  # add volcano vector
  geom_point(data = volcanoes_point, 
             aes(x = lon, y = lat, 
                 size = elevation), # point size depends on attribute value
             shape = 17,            # triangle
             color = "#22577a") +
  scale_size_continuous(name = "Volcanoes (m asl)") +       # legend title with units
  ggspatial::annotation_north_arrow(location = "br",        # bottom right
                                    which_north = "true") + # point to north pole
  ggspatial::annotation_scale(location = "bl",              # bottom left
                              width_hint = 0.5) +           # proportion of map area the scalebar should occupy
  labs(title = "Easter Island") +
  theme_minimal()
```